#!/bin/bash
#
# Copyright (C) 2011 Anders Håål, Ingenjorsbyn AB
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#lyx --export text README.lyx

if [ -f README.txt ] ; then
  cat  README.txt | sed -e "s/^<label:.*>/\n###. /"> readme.tmp
  old_IFS=$IFS
  IFS=$'\n'
  n=0
  while read line   
  do   
    echo $line | grep '^###.' >/dev/null
    if [ $? = 0 ] ; then
      n=$((++n))
      echo "$line"|sed -e "s/^###/$n/" 
    else      
      echo  "$line"
    fi
  done < readme.tmp | \
  # remove all <label:.....> entry
  sed -e "s/<label:.*>//g" | \
  # remove all [label: entry with [
  sed -e "s/\[label:/\[/g"| \
  # Join all chapter and section text that are on multiple lines
  sed -e '/^[0-9].*\./{N;/\n\s*[A-Za-z0-9].*$/s/\n/ /}' | \
  # Remove all multi spaces on a chapter or section line
  sed -e '/^[0-9].*\./s/\s\s*/ /g'| \
  # replace tab with 2 spaces
  sed "s/\t/  /g" | \
  fold -s  > README
    
  IFS=$old_IFS
#  rm -f README.txt
fi