#!/bin/bash
#
# Copyright (C) 2011 Anders Håål, Ingenjorsbyn AB
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

exportAs=pdf2

lyx=$(which lyx)
if [ "x$lyx" == "x" ] ; then
  echo "lyx must be installed to generate manuals"
  exit 1
fi

$lyx -e $exportAs Bischeck\ configuration\ guide.lyx 
$lyx -e $exportAs Bischeck\ installation\ and\ administration\ guide.lyx
$lyx -e $exportAs ReleaseNotes.lyx


